apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        google.cloud.container.build: >
            [{
              "container": "init",
              "steps": [{
                "name": "gcr.io/cloud-builders/docker",
                "dir": "init",
                "args": [
                  "build",
                  "-t",
                  "gcr.io/fresh-metrics-154816/init:8f4dfd28dbc51960d0bd2d463c23593cb878fd14",
                  "."
                ]
              }]
            },{
              "container": "container1",
              "steps": [{
                "name": "gcr.io/cloud-builders/docker",
                "dir": "container1",
                "args": [
                  "build",
                  "-t",
                  "gcr.io/fresh-metrics-154816/container1:v4",
                  "."
                ]
              }]
            },{
              "container": "container2",
              "steps": [{
                "name": "gcr.io/cloud-builders/docker",
                "dir": "container2",
                "args": [
                  "build",
                  "-t",
                  "gcr.io/fresh-metrics-154816/container2:v4",
                  "."
                ]
              }]
            }]
    spec:
      initContainers:
      - name: init
        image: gcr.io/fresh-metrics-154816/init:8f4dfd28dbc51960d0bd2d463c23593cb878fd14
      containers:
      - name: container1
        image: gcr.io/fresh-metrics-154816/container1:v4
      - name: container2
        image: gcr.io/fresh-metrics-154816/container2:v4
